# Generated by Django 3.1.6 on 2021-03-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listvehicle', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
