# Generated by Django 3.1.6 on 2021-03-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='desc',
        ),
    ]
