# Generated by Django 3.1.6 on 2021-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210314_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
