# Generated by Django 3.1.6 on 2021-03-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210314_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
