# Generated by Django 3.1.6 on 2021-03-15 05:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
