# Generated by Django 3.1.6 on 2021-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_ownerquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerquote',
            name='quote',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
