# Generated by Django 3.1.6 on 2021-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_ownerquote_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerquote',
            name='job_position',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
