# Generated by Django 3.1.6 on 2021-03-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_ownerquote_job_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerquote',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
