# Generated by Django 3.1.6 on 2021-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20210316_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerquote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
