# Generated by Django 3.1.6 on 2021-04-11 06:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20210316_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownercamper',
            old_name='overview',
            new_name='ownercamper',
        ),
        migrations.AddField(
            model_name='ownercamper',
            name='ownercaravan',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='new'),
            preserve_default=False,
        ),
    ]
