# Generated by Django 3.1.6 on 2021-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_experience_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
