# Generated by Django 3.1.6 on 2021-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='slug',
            field=models.SlugField(default='corado', unique=True),
            preserve_default=False,
        ),
    ]
