# Generated by Django 3.1.6 on 2021-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210322_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
