# Generated by Django 3.1.6 on 2021-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cartypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='cartypes',
            field=models.ManyToManyField(to='home.Cartypes'),
        ),
    ]
