# Generated by Django 3.1.6 on 2021-03-31 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Canceld', 'Canceld')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=150)),
                ('num_of_traveller', models.IntegerField(default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=150)),
                ('total', models.FloatField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
