# Generated by Django 3.1.6 on 2021-04-06 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.supply'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
