# Generated by Django 3.1.6 on 2021-04-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210406_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
