# Generated by Django 3.1.6 on 2021-04-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210410_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
    ]
