# Generated by Django 3.1.6 on 2021-04-11 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='transmission',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.transmission'),
            preserve_default=False,
        ),
    ]
