# Generated by Django 3.1.6 on 2021-04-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210419_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
