# Generated by Django 3.1.6 on 2021-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
