# Generated by Django 3.1.6 on 2021-04-19 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0031_auto_20210419_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.supply'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
