# Generated by Django 3.1.6 on 2021-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_reservation_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirm',
            field=models.BooleanField(null=True),
        ),
    ]
