# Generated by Django 3.1.6 on 2021-04-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210420_0152'),
        ('home', '0032_auto_20210419_1821'),
    ]

    operations = [
    ]
